"""empty message

Revision ID: 684669bd7e3b
Revises: 2ce7a30adf65
Create Date: 2025-08-04 10:20:06.809552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684669bd7e3b'
down_revision = '2ce7a30adf65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
