"""empty message

Revision ID: e3e8186e2fb4
Revises: 42c3d0f47742
Create Date: 2025-08-06 10:20:18.541012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e8186e2fb4'
down_revision = '42c3d0f47742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav', schema=None) as batch_op:
        batch_op.drop_constraint('fav_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav', schema=None) as batch_op:
        batch_op.create_unique_constraint('fav_name_key', ['name'])

    # ### end Alembic commands ###
